### ISSUE TITLE
Forcing a conf.py file for all branches and tags

### ISSUE THREAD

**Issue by anmolsjoshi** [sphinxcontrib-versioning-ng/sphinxcontrib-versioning#6]
Thank you for continuing the development of this project, I really appreciate it. 

An issue I've been running into is that my project has tags with an older version of conf.py file, this causes errors in building correct docs. Is it possible for all tags to use the same conf.py without manually editing the tags?

**Comment by anmolsjoshi** [comment]
Closing this issue. If anyone else has this issue, you can follow my [fork](https://github.com/anmolsjoshi/sphinxcontrib-versioning).

**Comment by epruesse** [comment]
Thank you @anmolsjoshi! The originally project has been moved to sphinx-contrib, where development will continue. Please open PRs over there. I will be deleting this org very soon.
